/* 北京版四年级上册 · 家侧检测 / 问答题库
 * 词表为常用教学词，可按学校进度在页面增删；不替代课本 Word List。
 */
window.ENGLISH_DESK_DATA = {
  title: "英语家侧 · 15–20 分钟",
  book: "北京版四年级上册",
  modes: {
    full: { label: "20 分钟", check: 5, oral: 5, read: 10 },
    short: { label: "15 分钟", check: 5, oral: 5, read: 5 },
  },
  weekHints: [
    { day: 1, check: "新课 5 词 · 汉→英", oral: "本周题卡 3 问", note: "开周" },
    { day: 2, check: "错词 + 新词 · 听写", oral: "同一题卡 · 逼说自己", note: "巩固" },
    { day: 3, check: "词填进句", oral: "看情景即兴 3 问", note: "活用" },
    { day: 4, check: "句型三步为主", oral: "短角色戏", note: "开口" },
    { day: 5, check: "本周 3 + 旧单元 2", oral: "今日一句", note: "滚动" },
    { day: 6, check: "错词复测 3′", oral: "可选 / 主题三句", note: "周末拉长阅读" },
    { day: 0, check: "错词复测 3′", oral: "可选 / 主题三句", note: "周末拉长阅读" },
  ],
  units: [
    {
      id: "u1",
      name: "Unit 1 Share and Care",
      currentLesson: 4,
      lessonTitle: "Lesson 4 Yoyo and Joe",
      themes: "天气与情绪 · 朋友陪伴 · Letters and Sounds",
      kaixinHint: "开心单词书：情绪 / 天气 / 朋友陪伴情景",
      words: [
        { en: "his", zh: "他的", src: "第4课", lesson: 4 },
        { en: "mouse", zh: "老鼠", src: "第4课", lesson: 4 },
        { en: "come", zh: "来", src: "第4课", lesson: 4 },
        { en: "have", zh: "有", src: "第4课", lesson: 4 },
        { en: "idea", zh: "主意", src: "第4课", lesson: 4 },
        { en: "stop", zh: "停止", src: "第4课", lesson: 4 },
        { en: "but", zh: "但是", src: "第4课", lesson: 4 },
        { en: "rainy", zh: "下雨的", src: "第4课", lesson: 4 },
        { en: "sunny", zh: "晴朗的", src: "第4课", lesson: 4 },
        { en: "wind", zh: "风", src: "第4课", lesson: 4 },
        { en: "rain", zh: "雨", src: "第4课", lesson: 4 },
        { en: "angry", zh: "生气的", src: "第3–4课", lesson: 3 },
        { en: "happy", zh: "高兴的", src: "第1–4课", lesson: 1 },
        { en: "sad", zh: "难过的", src: "第1–3课", lesson: 1 },
        { en: "worried", zh: "担心的", src: "第1–3课", lesson: 1 },
        { en: "excited", zh: "兴奋的", src: "第1–3课", lesson: 1 },
        { en: "feel", zh: "感觉", src: "第1课", lesson: 1 },
        { en: "matter", zh: "麻烦；问题", src: "第2课", lesson: 2 },
        { en: "together", zh: "一起", src: "第2–3课", lesson: 2 },
      ],
      patterns: [
        {
          id: "like-rain",
          label: "I like / don't like rainy days",
          steps: [
            "原句：I like rainy days. / I don't like rainy days.",
            "换词：rainy → sunny / windy；或换成 foods / sports",
            "说自己：你喜欢下雨天吗？因为什么？",
          ],
          frame: "I like / don't like ____ days because ____.",
          demos: [
            { role: "boyChild", text: "I like rainy days." },
            { role: "girlChild", text: "I don't like rainy days." },
            { role: "boyChild", text: "I like rainy days because I can read at home." },
          ],
        },
        {
          id: "here-comes",
          label: "Here comes the rain / wind",
          steps: [
            "原句：Here comes the rain. / Here comes the wind.",
            "换词：rain → bus / my dad / the wind",
            "说自己：用 Here comes… 说眼前刚发生的一件事",
          ],
          frame: "Here comes ____.",
          demos: [
            { role: "adultFemale", text: "Here comes the rain." },
            { role: "adultMale", text: "Here comes the wind." },
            { role: "boyChild", text: "Here comes my dad." },
          ],
        },
        {
          id: "gets",
          label: "Yoyo gets angry / is not happy",
          steps: [
            "原句：Yoyo is not happy. / Yoyo gets angry.",
            "换词：Yoyo → I / Tom；angry → happy / excited / sad",
            "说自己：今天什么事让你 get ____？",
          ],
          frame: "I get / feel ____ when ____.",
          demos: [
            { role: "boyChild", text: "Yoyo is not happy." },
            { role: "boyChild", text: "Yoyo gets angry." },
            { role: "girlChild", text: "I feel happy when the sun comes out." },
          ],
        },
      ],
      questions: [
        {
          ask: "Do you like rainy days? Why?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "Yes. I like rainy days because I can read books at home." },
        },
        {
          ask: "How do you feel when it rains?",
          asker: "adultMale",
          sample: { role: "girlChild", text: "I feel a little sad, but I feel warm at home." },
        },
        {
          ask: "What do you do with your friend on a rainy day?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "We read a story together." },
        },
      ],
      roleplay: "下雨了，一个朋友不高兴；你安慰他，并提议一起做一件室内的事。",
      dialogues: [
        { role: "boyChild", name: "Yoyo", text: "Oh no. Here comes the rain. I don't like rainy days." },
        { role: "boyChild", name: "Joe", text: "Don't be sad, Yoyo. I have an idea." },
        { role: "boyChild", name: "Joe", text: "Let's read a book together." },
        { role: "boyChild", name: "Yoyo", text: "Thank you, Joe!" },
      ],
      readPrompts: [
        { role: "adultFemale", text: "Who is in the story?" },
        { role: "adultFemale", text: "What happened?" },
        { role: "adultMale", text: "How does Yoyo feel?" },
      ],
    },
    {
      id: "u2",
      name: "Unit 2 Be Good Friends",
      themes: "朋友 · 一起读 · 帮助 · 休息",
      kaixinHint: "开心单词书：一起玩 / 读书 / 生病休息",
      words: [
        { en: "read", zh: "读", src: "课本" },
        { en: "story", zh: "故事", src: "课本" },
        { en: "together", zh: "一起", src: "课本" },
        { en: "help", zh: "帮助", src: "课本" },
        { en: "share", zh: "分享", src: "课本" },
        { en: "should", zh: "应该", src: "课本" },
        { en: "rest", zh: "休息", src: "课本" },
        { en: "ill", zh: "生病的", src: "课本" },
        { en: "remember", zh: "记住", src: "课本" },
        { en: "poem", zh: "诗", src: "课本" },
        { en: "friend", zh: "朋友", src: "课本" },
        { en: "polite", zh: "礼貌的", src: "拓展" },
        { en: "kind", zh: "友好的", src: "拓展" },
        { en: "book", zh: "书", src: "拓展" },
      ],
      patterns: [
        {
          id: "doing",
          label: "What are you doing?",
          steps: [
            "原句：What are you doing? → I'm reading.",
            "换词：reading → drawing / playing / helping Mum",
            "说自己：现在正在做什么",
          ],
          frame: "I'm ____ing.",
          demos: [
            { role: "adultFemale", text: "What are you doing?" },
            { role: "boyChild", text: "I'm reading." },
            { role: "girlChild", text: "I'm helping Mum." },
          ],
        },
        {
          id: "can",
          label: "Can I … with you?",
          steps: [
            "原句：Can I read it with you? → Sure.",
            "换词：read → play / walk / sing",
            "说自己：邀请家人一起做一事",
          ],
          frame: "Can I ____ with you?",
          demos: [
            { role: "girlChild", text: "Can I read it with you?" },
            { role: "boyChild", text: "Sure. We can read it together." },
          ],
        },
        {
          id: "should",
          label: "You should…",
          steps: [
            "原句：You should have a good rest.",
            "换词：have a good rest → drink water / see a doctor",
            "说自己：给家人一条善意建议",
          ],
          frame: "You should ____.",
          demos: [
            { role: "adultFemale", text: "You should have a good rest." },
            { role: "adultMale", text: "You should drink some water." },
          ],
        },
      ],
      questions: [
        {
          ask: "What are you doing now?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I'm reading a storybook." },
        },
        {
          ask: "Can I read / play with you?",
          asker: "girlChild",
          sample: { role: "boyChild", text: "Sure. Let's play together." },
        },
        {
          ask: "What should a good friend do?",
          asker: "adultMale",
          sample: { role: "girlChild", text: "A good friend should help you." },
        },
      ],
      roleplay: "朋友生病了，你打电话关心并给出建议。",
      dialogues: [
        { role: "girlChild", name: "You", text: "Hello. How do you feel today?" },
        { role: "boyChild", name: "Friend", text: "I'm ill. I feel tired." },
        { role: "girlChild", name: "You", text: "Oh. You should have a good rest." },
        { role: "adultFemale", name: "Mum", text: "Please drink a lot of water." },
      ],
      readPrompts: [
        { role: "adultFemale", text: "Who are the friends?" },
        { role: "adultFemale", text: "What should the friend do?" },
      ],
    },
    {
      id: "u3",
      name: "Unit 3 Be a Nice Person",
      themes: "礼貌 · 请求 · 道歉",
      kaixinHint: "开心单词书：借东西 / 道歉 / 请帮忙",
      words: [
        { en: "help", zh: "帮助", src: "课本" },
        { en: "please", zh: "请", src: "课本" },
        { en: "excuse", zh: "劳驾", src: "课本" },
        { en: "sorry", zh: "抱歉", src: "课本" },
        { en: "could", zh: "可以（更礼貌）", src: "课本" },
        { en: "banana", zh: "香蕉", src: "课本" },
        { en: "pencil", zh: "铅笔", src: "拓展" },
        { en: "borrow", zh: "借入", src: "拓展" },
        { en: "thank", zh: "感谢", src: "拓展" },
        { en: "nice", zh: "友好的", src: "拓展" },
        { en: "careful", zh: "小心的", src: "拓展" },
        { en: "wait", zh: "等待", src: "拓展" },
      ],
      patterns: [
        {
          id: "helpme",
          label: "Can you help me, please?",
          steps: [
            "原句：Can you help me, please?",
            "换词：help me → open the door / carry the books",
            "说自己：向家人礼貌求助一件事",
          ],
          frame: "Can you ____, please?",
          demos: [
            { role: "girlChild", text: "Can you help me, please?" },
            { role: "adultMale", text: "Sure. Let me help you." },
          ],
        },
        {
          id: "sorry",
          label: "I'm sorry.",
          steps: [
            "原句：I'm sorry.",
            "换词：补原因 I'm sorry I'm late.",
            "说自己：今天有没有想道歉的小事",
          ],
          frame: "I'm sorry ____.",
          demos: [
            { role: "boyChild", text: "I'm sorry." },
            { role: "boyChild", text: "I'm sorry I'm late." },
          ],
        },
        {
          id: "could",
          label: "Could I have…?",
          steps: [
            "原句：Could I have a banana, please?",
            "换词：banana → apple / pencil / water",
            "说自己：礼貌要一样东西",
          ],
          frame: "Could I have ____, please?",
          demos: [
            { role: "girlChild", text: "Could I have a banana, please?" },
            { role: "adultFemale", text: "Yes, of course." },
          ],
        },
      ],
      questions: [
        {
          ask: "Can you help me, please?",
          asker: "girlChild",
          sample: { role: "adultMale", text: "Yes. What can I do for you?" },
        },
        {
          ask: "When do you say sorry?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I say sorry when I make a mistake." },
        },
        {
          ask: "Could I have a banana / pencil, please?",
          asker: "boyChild",
          sample: { role: "adultFemale", text: "Yes, please. Here you are." },
        },
      ],
      roleplay: "在家里礼貌点一份食物或借一支笔。",
      dialogues: [
        { role: "boyChild", name: "You", text: "Excuse me. Could I have a pencil, please?" },
        { role: "adultFemale", name: "Mum", text: "Yes. Here you are." },
        { role: "boyChild", name: "You", text: "Thank you." },
        { role: "adultFemale", name: "Mum", text: "You're welcome." },
      ],
      readPrompts: [
        { role: "adultFemale", text: "What does the child ask for?" },
        { role: "adultMale", text: "Is the child polite?" },
      ],
    },
    {
      id: "u5",
      name: "Unit 5 Enjoy Eating",
      themes: "点餐 · 食物 · 餐桌礼仪",
      kaixinHint: "开心单词书：点餐 / 食物饮料 / 餐桌",
      words: [
        { en: "chicken", zh: "鸡肉", src: "课本" },
        { en: "salad", zh: "沙拉", src: "课本" },
        { en: "chopsticks", zh: "筷子", src: "课本" },
        { en: "would", zh: "想要（委婉）", src: "课本" },
        { en: "like", zh: "喜欢；想要", src: "课本" },
        { en: "drink", zh: "饮料；喝", src: "课本" },
        { en: "soup", zh: "汤", src: "拓展" },
        { en: "rice", zh: "米饭", src: "拓展" },
        { en: "noodles", zh: "面条", src: "拓展" },
        { en: "fruit", zh: "水果", src: "拓展" },
        { en: "water", zh: "水", src: "拓展" },
        { en: "juice", zh: "果汁", src: "拓展" },
        { en: "clean", zh: "干净的", src: "拓展" },
        { en: "table", zh: "桌子", src: "拓展" },
      ],
      patterns: [
        {
          id: "wouldlike",
          label: "What would you like…?",
          steps: [
            "原句：What would you like to have? → I'd like some chicken.",
            "换词：chicken → salad / soup / noodles",
            "说自己：今晚想吃什么",
          ],
          frame: "I'd like ____.",
          demos: [
            { role: "adultFemale", text: "What would you like to have?" },
            { role: "boyChild", text: "I'd like some chicken." },
            { role: "girlChild", text: "I'd like some fruit salad." },
          ],
        },
        {
          id: "wouldyou",
          label: "Would you like…?",
          steps: [
            "原句：Would you like some water? → Yes, please. / No, thank you.",
            "换词：water → juice / rice",
            "说自己：招待家人喝点什么",
          ],
          frame: "Would you like ____?",
          demos: [
            { role: "adultMale", text: "Would you like some water?" },
            { role: "girlChild", text: "Yes, please." },
            { role: "boyChild", text: "No, thank you." },
          ],
        },
        {
          id: "table",
          label: "Keep the table clean",
          steps: [
            "原句：Please don't play with the chopsticks.",
            "换词：说一条餐桌礼貌",
            "说自己：你家饭桌有什么规矩",
          ],
          frame: "Please ____. / Keep ____ clean.",
          demos: [
            { role: "adultFemale", text: "Please don't play with the chopsticks." },
            { role: "adultMale", text: "Keep the table clean." },
          ],
        },
      ],
      questions: [
        {
          ask: "What would you like to have?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I'd like some noodles, please." },
        },
        {
          ask: "Would you like some water?",
          asker: "adultMale",
          sample: { role: "girlChild", text: "Yes, please. Thank you." },
        },
        {
          ask: "How do you keep the table clean?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I don't play with the chopsticks." },
        },
      ],
      roleplay: "假装在餐厅点餐，完成 4 个来回。",
      dialogues: [
        { role: "adultFemale", name: "Waiter", text: "What would you like to have?" },
        { role: "boyChild", name: "You", text: "I'd like some chicken, please." },
        { role: "adultFemale", name: "Waiter", text: "Would you like some juice?" },
        { role: "boyChild", name: "You", text: "Yes, please." },
      ],
      readPrompts: [
        { role: "adultFemale", text: "What food do they order?" },
        { role: "adultMale", text: "How do they keep the table clean?" },
      ],
    },
    {
      id: "u6",
      name: "Unit 6 Get Close to Nature",
      themes: "自然 · 农场 · 旅行",
      kaixinHint: "开心单词书：农场 / 天气 / 动植物",
      words: [
        { en: "nature", zh: "自然", src: "课本" },
        { en: "farm", zh: "农场", src: "课本" },
        { en: "snow", zh: "雪", src: "课本" },
        { en: "water", zh: "水", src: "课本" },
        { en: "trip", zh: "旅行", src: "课本" },
        { en: "live", zh: "生活；居住", src: "课本" },
        { en: "without", zh: "没有", src: "课本" },
        { en: "plant", zh: "植物", src: "拓展" },
        { en: "animal", zh: "动物", src: "拓展" },
        { en: "river", zh: "河", src: "拓展" },
        { en: "tree", zh: "树", src: "拓展" },
        { en: "sun", zh: "太阳", src: "拓展" },
        { en: "wind", zh: "风", src: "拓展" },
        { en: "love", zh: "爱", src: "拓展" },
      ],
      patterns: [
        {
          id: "without",
          label: "We can't live without…",
          steps: [
            "原句：We can't live without nature / water.",
            "换词：water → air / plants / the sun",
            "说自己：你觉得什么最不能缺少",
          ],
          frame: "We can't live without ____.",
          demos: [
            { role: "adultMale", text: "We can't live without water." },
            { role: "adultFemale", text: "We can't live without nature." },
          ],
        },
        {
          id: "see",
          label: "I can see…",
          steps: [
            "原句：在农场 / 自然里看到什么",
            "换词：trees / animals / snow / a river",
            "说自己：最近一次户外看见了什么",
          ],
          frame: "I can see ____.",
          demos: [
            { role: "boyChild", text: "I can see a river." },
            { role: "girlChild", text: "I can see many trees." },
          ],
        },
        {
          id: "like",
          label: "I like … because…",
          steps: [
            "原句：I love this trip.",
            "换词：说明喜欢的原因 because…",
            "说自己：喜欢自然里的哪一样",
          ],
          frame: "I like ____ because ____.",
          demos: [
            { role: "boyChild", text: "I love this trip." },
            { role: "girlChild", text: "I like the farm because I can see animals." },
          ],
        },
      ],
      questions: [
        {
          ask: "What can you see in nature?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I can see trees, birds and a river." },
        },
        {
          ask: "What can't we live without?",
          asker: "adultMale",
          sample: { role: "girlChild", text: "We can't live without water." },
        },
        {
          ask: "Do you like the farm / snow? Why?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I like the farm because I can see animals." },
        },
      ],
      roleplay: "介绍一次去公园或农场，说看到了什么。",
      dialogues: [
        { role: "adultMale", name: "Dad", text: "What can you see on the farm?" },
        { role: "girlChild", name: "You", text: "I can see cows and trees." },
        { role: "adultFemale", name: "Mum", text: "Do you like this trip?" },
        { role: "girlChild", name: "You", text: "Yes. I love this trip." },
      ],
      readPrompts: [
        { role: "adultFemale", text: "What can you see?" },
        { role: "adultMale", text: "Why do you like nature?" },
      ],
    },
    {
      id: "u7",
      name: "Unit 7 Be Together",
      themes: "新年 · 春节 · 元宵",
      kaixinHint: "开心单词书：生日 / 春节 / 聚会 / 许愿",
      words: [
        { en: "new", zh: "新的", src: "课本" },
        { en: "year", zh: "年", src: "课本" },
        { en: "festival", zh: "节日", src: "课本" },
        { en: "spring", zh: "春；春节相关", src: "课本" },
        { en: "lantern", zh: "灯笼", src: "课本" },
        { en: "wish", zh: "愿望", src: "课本" },
        { en: "riddle", zh: "谜语", src: "课本" },
        { en: "guess", zh: "猜", src: "课本" },
        { en: "happy", zh: "快乐的", src: "课本" },
        { en: "family", zh: "家庭", src: "拓展" },
        { en: "party", zh: "聚会", src: "拓展" },
        { en: "candle", zh: "蜡烛", src: "拓展" },
        { en: "together", zh: "一起", src: "拓展" },
        { en: "story", zh: "故事", src: "拓展" },
      ],
      patterns: [
        {
          id: "happy",
          label: "Happy …!",
          steps: [
            "原句：Happy New Year! / Happy Spring Festival!",
            "换词：换节日或生日 Happy birthday!",
            "说自己：给家人一句节日祝福",
          ],
          frame: "Happy ____!",
          demos: [
            { role: "adultMale", text: "Happy New Year!" },
            { role: "adultFemale", text: "Happy Spring Festival!" },
            { role: "girlChild", text: "Happy birthday!" },
          ],
        },
        {
          id: "wish",
          label: "I make a wish…",
          steps: [
            "原句：I make a wish.",
            "换词：说出愿望 I wish I can…",
            "说自己：你的一个小愿望",
          ],
          frame: "I wish ____.",
          demos: [
            { role: "boyChild", text: "I make a wish." },
            { role: "girlChild", text: "I wish I can read more books." },
          ],
        },
        {
          id: "festival",
          label: "What do you do at…?",
          steps: [
            "原句：春节 / 元宵做什么",
            "换词：eat / visit / guess riddles",
            "说自己：你家过节的一件事",
          ],
          frame: "At ____, we ____.",
          demos: [
            { role: "adultFemale", text: "What do you do at Spring Festival?" },
            { role: "boyChild", text: "At Spring Festival, we visit our family." },
          ],
        },
      ],
      questions: [
        {
          ask: "What festival is coming?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "Spring Festival is coming." },
        },
        {
          ask: "What do you do at Spring Festival?",
          asker: "adultMale",
          sample: { role: "girlChild", text: "We eat together and visit our family." },
        },
        {
          ask: "What is your wish?",
          asker: "adultFemale",
          sample: { role: "boyChild", text: "I wish I can be a good friend." },
        },
      ],
      roleplay: "介绍你们家过节的一天，说三件事。",
      dialogues: [
        { role: "adultMale", name: "Dad", text: "Happy Spring Festival!" },
        { role: "girlChild", name: "You", text: "Happy Spring Festival, Dad!" },
        { role: "adultFemale", name: "Mum", text: "What is your wish?" },
        { role: "girlChild", name: "You", text: "I wish we can be together." },
      ],
      readPrompts: [
        { role: "adultFemale", text: "What festival is it?" },
        { role: "adultMale", text: "What is the wish?" },
      ],
    },
  ],
};
