/* 北京版四年级上册 · 预习对话（对照课本 Look and say / 故事原文）
 * 角色：adultMale / adultFemale / boyChild / girlChild
 */
window.ENGLISH_DESK_PREVIEW = {
  u1: {
    1: {
      title: "How Do You Feel Today?",
      bookPages: [2, 3],
      focusTalk:
        "这一课上课前要会三件事。第一，别人问 How do you feel today，你会答。第二，会说 I'm worried、I'm happy、I'm excited。第三，听得懂 Dad 说 You're just in time，就是刚好赶到，没迟到。对话里有爸爸、王老师和同学，先听熟，上课举手就有底气。",
      keySentences: [
        { en: "How do you feel today?", zh: "你今天感觉怎么样？" },
        { en: "I'm a little worried.", zh: "我有一点担心。" },
        { en: "We are so happy.", zh: "我们非常开心。" },
        { en: "I'm so excited.", zh: "我非常兴奋。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Dad, I'm a little worried. Am I late?", zh: "爸爸，我有点担心。我迟到了吗？" },
        { name: "Dad", role: "adultMale", text: "Don't worry. You're just in time.", zh: "别担心。你刚好及时赶到。" },
        { name: "Miss Wang", role: "adultFemale", text: "Welcome back to school! How do you feel today?", zh: "欢迎回学校！你今天感觉怎么样？" },
        { name: "Students", role: "girlChild", text: "Thank you, Miss Wang. We are so happy.", zh: "谢谢王老师。我们非常开心。" },
        { name: "Guoguo", role: "girlChild", text: "Wow, I'm so excited. Look at our new classroom. It's big and cool.", zh: "哇，我好兴奋。看我们的新教室。又大又酷。" },
        { name: "Sara", role: "girlChild", text: "Yes, it is!", zh: "是的，真的是！" },
      ],
    },
    2: {
      title: "What's the Matter?",
      bookPages: [5, 6],
      focusTalk:
        "这一课最重要的是问别人怎么了：What's the matter？别人难过时你会说 You look sad。自己丢东西会说 I can't find…。好朋友会说 Let's look for him together。上课老师问你会不会安慰同学，你就用这几句。",
      keySentences: [
        { en: "What's the matter?", zh: "怎么了？" },
        { en: "You look sad.", zh: "你看起来很难过。" },
        { en: "I can't find my dog.", zh: "我找不到我的狗。" },
        { en: "Let's look for him together.", zh: "我们一起找他吧。" },
      ],
      lines: [
        { name: "Lingling", role: "girlChild", text: "What's the matter, Maomao? You look sad.", zh: "怎么了，毛毛？你看起来很难过。" },
        { name: "Maomao", role: "boyChild", text: "I can't find my dog Danny.", zh: "我找不到我的狗 Danny。" },
        { name: "Lingling", role: "girlChild", text: "Don't cry. Let's look for him together. What does Danny look like?", zh: "别哭。我们一起找他。Danny 长什么样？" },
        { name: "Maomao", role: "boyChild", text: "He's brown with a black nose.", zh: "它是棕色的，鼻子是黑的。" },
        { name: "Lingling", role: "girlChild", text: "Look. Is that Danny?", zh: "看。那是 Danny 吗？" },
        { name: "Maomao", role: "boyChild", text: "Oh, yes! Danny!", zh: "哦，是的！Danny！" },
        { name: "Danny", role: "boyChild", text: "Woof! Woof!", zh: "汪！汪！" },
        { name: "Lingling", role: "girlChild", text: "Are you happy now?", zh: "你现在开心了吗？" },
        { name: "Maomao", role: "boyChild", text: "Yes, I'm so happy. Thank you, Lingling.", zh: "是的，我非常开心。谢谢你，玲玲。" },
        { name: "Lingling", role: "girlChild", text: "I'm happy, too.", zh: "我也很开心。" },
      ],
    },
    3: {
      title: "Let's Take a Walk",
      bookPages: [8, 9],
      focusTalk:
        "这一课学生气了怎么办。妈妈会说 Please don't be angry. Let's take a walk。散完步会问 How do you feel now？你可以答 I feel better。还有 calm down，就是冷静下来。弟弟会道歉 I'm sorry，你会说 Let's fix it together。",
      keySentences: [
        { en: "Please don't be angry.", zh: "请别生气。" },
        { en: "Let's take a walk.", zh: "我们去散散步吧。" },
        { en: "How do you feel now?", zh: "你现在感觉怎么样？" },
        { en: "I feel better.", zh: "我感觉好些了。" },
        { en: "A walk always helps me calm down.", zh: "散步总能帮我冷静下来。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Mum!", zh: "妈妈！" },
        { name: "Mike", role: "boyChild", text: "Look at my new model plane!", zh: "看我的新飞机模型！" },
        { name: "Mum", role: "adultFemale", text: "What's the matter?", zh: "怎么了？" },
        { name: "Mum", role: "adultFemale", text: "Let me have a look.", zh: "让我看一看。" },
        { name: "Mike", role: "boyChild", text: "That's my favourite one!", zh: "那是我最喜欢的一个！" },
        { name: "Mum", role: "adultFemale", text: "Please don't be angry. Let's take a walk.", zh: "请别生气。我们去散散步吧。" },
        { name: "Mum", role: "adultFemale", text: "How do you feel now?", zh: "你现在感觉怎么样？" },
        { name: "Mike", role: "boyChild", text: "I feel better, Mum.", zh: "我感觉好些了，妈妈。" },
        { name: "Mum", role: "adultFemale", text: "That's great! A walk always helps me calm down.", zh: "太好了！散步总能帮我冷静下来。" },
        { name: "Brother", role: "boyChild", text: "I'm sorry, Mike. I just want to play with you.", zh: "对不起，Mike。我只是想和你一起玩。" },
        { name: "Mike", role: "boyChild", text: "It's OK. Let's fix it together.", zh: "没关系。我们一起修吧。" },
      ],
    },
    4: {
      title: "Yoyo and Joe",
      bookPages: [11, 12],
      focusTalk:
        "这是故事课。要会说 I love sunny days、I don't like windy days。朋友出主意说 I have an idea. Let's fly a kite。生气时说 Calm down。最后明白 every day could be fun。上课老师问故事大意，你就抓这几句。",
      keySentences: [
        { en: "I love sunny days!", zh: "我喜欢晴天！" },
        { en: "I don't like windy days.", zh: "我不喜欢大风天。" },
        { en: "I have an idea. Let's fly a kite.", zh: "我有一个主意。我们去放风筝吧。" },
        { en: "Calm down.", zh: "冷静下来。" },
        { en: "Every day could be fun.", zh: "每一天都可以很有趣。" },
      ],
      lines: [
        { name: "Yoyo", role: "boyChild", text: "I love sunny days!", zh: "我喜欢晴天！" },
        { name: "Joe", role: "boyChild", text: "Me, too.", zh: "我也是。" },
        { name: "Yoyo", role: "boyChild", text: "I don't like windy days.", zh: "我不喜欢大风天。" },
        { name: "Joe", role: "boyChild", text: "I have an idea. Let's fly a kite.", zh: "我有一个主意。我们去放风筝吧。" },
        { name: "Yoyo", role: "boyChild", text: "I love windy days now.", zh: "我现在喜欢大风天了。" },
        { name: "Yoyo", role: "boyChild", text: "I don't like rainy days!", zh: "我不喜欢下雨天！" },
        { name: "Joe", role: "boyChild", text: "Calm down. I have an idea.", zh: "冷静下来。我有一个主意。" },
        { name: "Yoyo", role: "boyChild", text: "Hooray! I love rainy days now.", zh: "太好了！我现在喜欢下雨天了。" },
        { name: "Yoyo", role: "boyChild", text: "It is a sunny day again! But now I know every day could be fun. Thank you, Joe!", zh: "又是晴天了！可我现在知道，每一天都可以很有趣。谢谢你，Joe！" },
      ],
    },
  },
  u2: {
    1: {
      title: "We Can Read It Together",
      bookPages: [16, 17],
      focusTalk:
        "这一课学一起读书。会问 What are you reading？会答 I'm reading a science book / a story book。会说 What's it about？和 We can read it together。interesting 是有趣。上课分享读什么书，就用这些句子。",
      keySentences: [
        { en: "What are you reading?", zh: "你在读什么？" },
        { en: "I'm reading a science book.", zh: "我在读一本科学书。" },
        { en: "What's it about?", zh: "它是关于什么的？" },
        { en: "We can read it together.", zh: "我们可以一起读。" },
      ],
      lines: [
        { name: "Maomao", role: "boyChild", text: "What are you reading, Mike?", zh: "你在读什么，Mike？" },
        { name: "Mike", role: "boyChild", text: "I'm reading a science book. I love science books.", zh: "我在读一本科学书。我爱科学书。" },
        { name: "Maomao", role: "boyChild", text: "What's it about?", zh: "它是关于什么的？" },
        { name: "Mike", role: "boyChild", text: "It's about animal eyes. Different animal eyes work in different ways.", zh: "是关于动物眼睛的。不同动物的眼睛工作方式不同。" },
        { name: "Maomao", role: "boyChild", text: "Sounds interesting.", zh: "听起来很有趣。" },
        { name: "Mike", role: "boyChild", text: "What are you reading?", zh: "你在读什么？" },
        { name: "Maomao", role: "boyChild", text: "I'm reading a story book. In this story, a boy has a magic brush. It can turn his drawings into real things.", zh: "我在读故事书。故事里一个男孩有一支神笔，能把画变成真的。" },
        { name: "Mike", role: "boyChild", text: "Cool! Can I read it with you?", zh: "酷！我可以和你一起读吗？" },
        { name: "Maomao", role: "boyChild", text: "Sure, we can read it together.", zh: "当然，我们可以一起读。" },
      ],
    },
    2: {
      title: "Let Me Help You",
      bookPages: [19, 20],
      focusTalk:
        "这一课是帮忙。果果记不住诗，玲玲说 Let me help you。诗很难可以说 It's so hard。试一试可以说 Let me try。May I try 也是请求试一试。朋友帮你记住了，要会说 Thank you so much。",
      keySentences: [
        { en: "What's the matter?", zh: "怎么了？" },
        { en: "I can't remember the poem. It's so hard.", zh: "我记不住这首诗。太难了。" },
        { en: "Let me help you.", zh: "让我来帮助你。" },
        { en: "Let me try.", zh: "让我试试。" },
      ],
      lines: [
        { name: "Lingling", role: "girlChild", text: "What's the matter, Guoguo?", zh: "怎么了，果果？" },
        { name: "Guoguo", role: "girlChild", text: "I can't remember the poem. It's so hard.", zh: "我记不住这首诗。太难了。" },
        { name: "Lingling", role: "girlChild", text: "Let me help you.", zh: "让我来帮助你。" },
        { name: "Lingling", role: "girlChild", text: "You can remember the first word of every line.", zh: "你可以记住每一行的第一个词。" },
        { name: "Guoguo", role: "girlChild", text: "I still can't remember it.", zh: "我还是记不住。" },
        { name: "Lingling", role: "girlChild", text: "You can draw a picture for the poem. It may help.", zh: "你可以为这首诗画一幅画。也许有帮助。" },
        { name: "Guoguo", role: "girlChild", text: "Let me try.", zh: "让我试试。" },
        { name: "Guoguo", role: "girlChild", text: "It works, Lingling! It works! I can remember it now.", zh: "管用了，玲玲！管用了！我现在能记住了。" },
        { name: "Lingling", role: "girlChild", text: "Good for you!", zh: "太棒了！" },
        { name: "Guoguo", role: "girlChild", text: "Thank you so much. It's great to have a friend like you.", zh: "太谢谢你了。有你这样的朋友真好。" },
      ],
    },
    3: {
      title: "You Should Have a Good Rest",
      bookPages: [22, 23],
      focusTalk:
        "这一课是打电话和照顾生病的朋友。会说 May I speak to Lingling？听说生病要说 I'm sorry to hear that。建议别人 You should have a good rest。should 就是应该。还会说 drink some warm water。",
      keySentences: [
        { en: "May I speak to Lingling?", zh: "我可以和玲玲讲话吗？" },
        { en: "She is ill today.", zh: "她今天生病了。" },
        { en: "I'm sorry to hear that.", zh: "听到这个我很难过。" },
        { en: "You should have a good rest.", zh: "你应该好好休息。" },
      ],
      lines: [
        { name: "Guoguo", role: "girlChild", text: "Hello, Aunt. This is Guoguo. May I speak to Lingling?", zh: "你好，阿姨。我是果果。我可以和玲玲讲话吗？" },
        { name: "Aunt", role: "adultFemale", text: "Sorry, Guoguo. Lingling is sleeping. She is ill today.", zh: "对不起，果果。玲玲在睡觉。她今天生病了。" },
        { name: "Guoguo", role: "girlChild", text: "I'm sorry to hear that. May I call her later?", zh: "听到这个我很难过。我可以稍后再打给她吗？" },
        { name: "Aunt", role: "adultFemale", text: "Yes. That's fine.", zh: "可以。没问题。" },
        { name: "Guoguo", role: "girlChild", text: "How are you feeling, Lingling?", zh: "你感觉怎么样，玲玲？" },
        { name: "Lingling", role: "girlChild", text: "Not so good. I have a bad cold. I can't go to school tomorrow.", zh: "不太好。我得了重感冒。明天不能去上学。" },
        { name: "Guoguo", role: "girlChild", text: "Don't worry. You should have a good rest and drink some warm water now.", zh: "别担心。你现在应该好好休息，喝点温水。" },
        { name: "Lingling", role: "girlChild", text: "Thank you, Guoguo.", zh: "谢谢你，果果。" },
      ],
    },
    4: {
      title: "A Cupcake",
      bookPages: [25, 26],
      focusTalk:
        "故事课讲分享。想吃蛋糕说 May I have a cupcake, please？心里会问 Should I？好朋友 Joe 总是分享，所以 Yoyo 也应该 share。上课讨论好朋友该不该分享，用 should 和 share。",
      keySentences: [
        { en: "May I have a cupcake, please?", zh: "请问我可以要一个杯子蛋糕吗？" },
        { en: "I should share it with him.", zh: "我应该和他分享。" },
        { en: "Joe is my best friend.", zh: "Joe 是我最好的朋友。" },
      ],
      lines: [
        { name: "Yoyo", role: "boyChild", text: "Oh, cakes! I love cakes!", zh: "哦，蛋糕！我爱蛋糕！" },
        { name: "Yoyo", role: "boyChild", text: "May I have a cupcake, please?", zh: "请问我可以要一个杯子蛋糕吗？" },
        { name: "Seller", role: "adultFemale", text: "Yes. Here you go.", zh: "好的。给你。" },
        { name: "Yoyo", role: "boyChild", text: "Thank you.", zh: "谢谢。" },
        { name: "Yoyo", role: "boyChild", text: "Oh, my love! I can't wait to put you in my mouth.", zh: "哦，我的最爱！我等不及要吃你了。" },
        { name: "Yoyo", role: "boyChild", text: "Should I? My little cake? It's too small to share. I should eat it all.", zh: "该不该呢？我的小蛋糕？太小了不好分享。我该全吃掉。" },
        { name: "Yoyo", role: "boyChild", text: "Wait. Joe loves cakes, too. Joe is my best friend. I should share it with him.", zh: "等等。Joe 也爱蛋糕。Joe 是我最好的朋友。我应该和他分享。" },
        { name: "Yoyo", role: "boyChild", text: "Should I? Joe may be sad. He always shares good things with me.", zh: "该不该呢？Joe 也许会难过。他总是和我分享好东西。" },
        { name: "Yoyo", role: "boyChild", text: "Can I? Oh, no!", zh: "可以吗？哦，不！" },
      ],
    },
  },
  u3: {
    1: {
      title: "Can You Help Me, Please?",
      bookPages: [30, 31],
      focusTalk:
        "礼貌请求是这一课的核心。先说 Excuse me，再说 Can you help me, please？想借东西说 May I use your bat？坏了会说 That's OK! We can fix it。please 和 Excuse me 上课一定要说出来。",
      keySentences: [
        { en: "Excuse me, can you help me, please?", zh: "打扰一下，请问你能帮我吗？" },
        { en: "May I use your bat?", zh: "我可以用你的球拍吗？" },
        { en: "Sure. Here you are.", zh: "当然。给你。" },
        { en: "We can fix it.", zh: "我们可以修好它。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Excuse me, Baobao, can you help me, please?", zh: "打扰一下，宝宝，请问你能帮我吗？" },
        { name: "Baobao", role: "boyChild", text: "Sure, Mike. What can I do for you?", zh: "当然，Mike。我能为你做什么？" },
        { name: "Mike", role: "boyChild", text: "I can't find my ping-pong bat. May I use your bat?", zh: "我找不到我的乒乓球拍。我可以用你的球拍吗？" },
        { name: "Baobao", role: "boyChild", text: "Sure. Here you are.", zh: "当然。给你。" },
        { name: "Mike", role: "boyChild", text: "Thank you.", zh: "谢谢。" },
        { name: "Mike", role: "boyChild", text: "Oh, no!", zh: "哦，不！" },
        { name: "Mike", role: "boyChild", text: "I'm so sorry, Baobao!", zh: "非常对不起，宝宝！" },
        { name: "Baobao", role: "boyChild", text: "Don't worry. Let me see.", zh: "别担心。让我看看。" },
        { name: "Baobao", role: "boyChild", text: "That's OK! We can fix it.", zh: "没关系！我们可以修好它。" },
      ],
    },
    2: {
      title: "Excuse Me",
      bookPages: [33, 34],
      focusTalk:
        "挤地铁、开门都要有礼貌。Would you please open the door for me？对方说 Sure. No problem。不礼貌会被提醒 You should say Excuse me。还要 stand in line and wait，让别人先下车。",
      keySentences: [
        { en: "Excuse me, would you please open the door for me?", zh: "打扰一下，请你帮我开一下门好吗？" },
        { en: "Sure. No problem.", zh: "当然。没问题。" },
        { en: "You should say \"Excuse me.\"", zh: "你应该说「打扰一下」。" },
        { en: "We should stand in line and wait.", zh: "我们应该排队等候。" },
      ],
      lines: [
        { name: "Yangyang", role: "boyChild", text: "Excuse me, would you please open the door for me?", zh: "打扰一下，请你帮我开一下门好吗？" },
        { name: "Helper", role: "adultFemale", text: "Sure. No problem.", zh: "当然。没问题。" },
        { name: "Yangyang", role: "boyChild", text: "Thank you.", zh: "谢谢。" },
        { name: "Helper", role: "adultFemale", text: "You're welcome.", zh: "不客气。" },
        { name: "Mum", role: "adultFemale", text: "Don't push, Yangyang. It's not polite. You should say \"Excuse me.\"", zh: "别挤，阳阳。这样不礼貌。你应该说「打扰一下」。" },
        { name: "Yangyang", role: "boyChild", text: "I see. Excuse me.", zh: "我明白了。打扰一下。" },
        { name: "Yangyang", role: "boyChild", text: "We must hurry, Mum.", zh: "我们得快点，妈妈。" },
        { name: "Mum", role: "adultFemale", text: "Let people get off first. We should stand in line and wait.", zh: "让别人先下车。我们应该排队等候。" },
        { name: "Yangyang", role: "boyChild", text: "Sorry, Mum.", zh: "对不起，妈妈。" },
      ],
    },
    3: {
      title: "I'm Sorry",
      bookPages: [36, 37],
      focusTalk:
        "这一课对比粗鲁和礼貌。粗鲁是 Hey, you, sweep the floor！礼貌是 Could you sweep the floor, please？做错了要说 I'm sorry。老师会强调 You should speak in a polite way。",
      keySentences: [
        { en: "Could you sweep the floor, please?", zh: "请你扫一下地好吗？" },
        { en: "You should speak in a polite way.", zh: "你应该用礼貌的方式说话。" },
        { en: "I'm sorry, everyone.", zh: "对不起，大家。" },
        { en: "Let's do it together.", zh: "我们一起做吧。" },
      ],
      lines: [
        { name: "Baobao", role: "boyChild", text: "Hey, you, sweep the floor!", zh: "嘿，你，扫地！" },
        { name: "Miss Wang", role: "adultFemale", text: "You should speak in a polite way.", zh: "你应该用礼貌的方式说话。" },
        { name: "Miss Wang", role: "adultFemale", text: "Could you sweep the floor, please, Baobao?", zh: "请你扫一下地好吗，宝宝？" },
        { name: "Classmate", role: "girlChild", text: "Sure.", zh: "当然。" },
        { name: "Miss Wang", role: "adultFemale", text: "Could you get me some water, please, Baobao? I'd like to clean the blackboard.", zh: "请你给我拿点水好吗，宝宝？我想擦黑板。" },
        { name: "Classmate", role: "girlChild", text: "Sure, no problem.", zh: "当然，没问题。" },
        { name: "Baobao", role: "boyChild", text: "I see. I should be polite.", zh: "我明白了。我应该有礼貌。" },
        { name: "Baobao", role: "boyChild", text: "I'm sorry, everyone.", zh: "对不起，大家。" },
        { name: "Classmates", role: "girlChild", text: "Let's do it together.", zh: "我们一起做吧。" },
      ],
    },
    4: {
      title: "Could I Have a Banana, Please?",
      bookPages: [39, 40],
      focusTalk:
        "故事对比没礼貌和有礼貌。没礼貌说 Hey, I want a banana。有礼貌说 Excuse me. Could I have a banana, please？Would you please…？也是客气请求。Could I / Would you 是本课句型重点。",
      keySentences: [
        { en: "Excuse me. Could I have a banana, please?", zh: "打扰一下。请问我可以要一根香蕉吗？" },
        { en: "Would you please give me a banana?", zh: "请你给我一根香蕉好吗？" },
        { en: "Sure, no problem.", zh: "当然，没问题。" },
      ],
      lines: [
        { name: "Narrator", role: "adultFemale", text: "Two little monkeys are hungry. Here comes Mr Horse.", zh: "两只小猴子饿了。马先生来了。" },
        { name: "Monkey A", role: "boyChild", text: "Hey. Where can I get some food?", zh: "嘿。我在哪儿能弄到吃的？" },
        { name: "Monkey B", role: "girlChild", text: "Excuse me, Mr Horse. Where can I get some food?", zh: "打扰一下，马先生。我在哪儿能弄到吃的？" },
        { name: "Mr Horse", role: "adultMale", text: "Well, there are some banana trees in the garden over there.", zh: "嗯，那边花园里有些香蕉树。" },
        { name: "Monkey B", role: "girlChild", text: "Thank you.", zh: "谢谢。" },
        { name: "Monkey A", role: "boyChild", text: "Hey, I want a banana!", zh: "嘿，我要一根香蕉！" },
        { name: "Monkey B", role: "girlChild", text: "Excuse me, Mr Dog. Could I have a banana, please?", zh: "打扰一下，狗先生。请问我可以要一根香蕉吗？" },
        { name: "Mr Dog", role: "adultMale", text: "Sure, no problem.", zh: "当然，没问题。" },
        { name: "Monkey B", role: "girlChild", text: "Thank you.", zh: "谢谢。" },
        { name: "Monkey B", role: "girlChild", text: "Sorry, Mr Dog. Would you please give me a banana?", zh: "对不起，狗先生。请你给我一根香蕉好吗？" },
        { name: "Mr Dog", role: "adultMale", text: "Yes. Please go and get some.", zh: "可以。请去拿一些吧。" },
        { name: "Monkey B", role: "girlChild", text: "Thank you so much.", zh: "太谢谢你了。" },
      ],
    },
  },
  u4: {
    1: {
      title: "Revision A",
      bookPages: [44, 45],
      focusTalk:
        "复习课把心情词和安慰用语串起来。会读这首小诗：Sometimes we feel happy / sad / excited / angry。难过时 Don't worry，生气时 Calm down，Take a walk。上课朗读和表演时用这些句子。",
      keySentences: [
        { en: "Sometimes we feel happy.", zh: "有时我们感到开心。" },
        { en: "Don't worry!", zh: "别担心！" },
        { en: "Calm down!", zh: "冷静下来！" },
        { en: "Take a walk.", zh: "去散散步。" },
      ],
      lines: [
        { name: "Reader", role: "girlChild", text: "Sometimes we feel happy,", zh: "有时我们感到开心，" },
        { name: "Reader", role: "girlChild", text: "Sometimes we feel sad,", zh: "有时我们感到难过，" },
        { name: "Reader", role: "girlChild", text: "Sometimes we feel excited,", zh: "有时我们感到兴奋，" },
        { name: "Reader", role: "girlChild", text: "Sometimes we feel angry.", zh: "有时我们感到生气。" },
        { name: "Reader", role: "boyChild", text: "We may have different feelings, and they are all OK.", zh: "我们可能有不同的感受，它们都没关系。" },
        { name: "Reader", role: "girlChild", text: "When we are sad, we can cry. But I would say, Don't worry!", zh: "难过时我们可以哭。可我会说：别担心！" },
        { name: "Reader", role: "boyChild", text: "Talk to our family and friends. Their love can make us warm and safe.", zh: "和家人朋友说说话。他们的爱让我们温暖又安全。" },
        { name: "Reader", role: "girlChild", text: "When we are angry, we can shout. But I would say, Calm down! Take a walk. Everything will be OK.", zh: "生气时我们可以喊。可我会说：冷静！去散步。一切都会好的。" },
      ],
    },
    2: {
      title: "Revision B",
      bookPages: [46, 47],
      focusTalk:
        "这一课复习礼貌用语：excuse me、sorry、please、thank you，还有 May I…？Could you…？以及 Let me help you、You should…、Don't be angry。预习时把这些短句读熟，单元复习课就不慌。",
      keySentences: [
        { en: "Excuse me.", zh: "打扰一下。" },
        { en: "May I … ?", zh: "我可以……吗？" },
        { en: "Could you … ?", zh: "你能……吗？" },
        { en: "Let me help you.", zh: "让我来帮助你。" },
        { en: "Don't be angry. Let's take a walk.", zh: "别生气。我们去散散步吧。" },
      ],
      lines: [
        { name: "Teacher", role: "adultFemale", text: "Excuse me. May I pass, please?", zh: "打扰一下。请问我可以过去吗？" },
        { name: "Student", role: "boyChild", text: "Sorry. Please wait.", zh: "对不起。请等一等。" },
        { name: "Teacher", role: "adultFemale", text: "Could you help me, please?", zh: "请问你能帮我吗？" },
        { name: "Student", role: "girlChild", text: "Sure. Let me help you.", zh: "当然。让我来帮助你。" },
        { name: "Friend", role: "girlChild", text: "Don't worry. You should stay at home and drink some warm water.", zh: "别担心。你应该待在家里，喝点温水。" },
        { name: "Mum", role: "adultFemale", text: "Don't be angry. Let's take a walk.", zh: "别生气。我们去散散步吧。" },
        { name: "Child", role: "boyChild", text: "Thank you!", zh: "谢谢！" },
      ],
    },
  },
  u5: {
    1: {
      title: "I'd Like Some Chicken",
      bookPages: [50, 51],
      focusTalk:
        "点餐句型：What would you like…？答 I'd like some chicken / some tomatoes / some orange juice。没有时可以说 How about grape juice？healthy food 是健康食品。上课模拟点餐就靠 I'd like。",
      keySentences: [
        { en: "What would you like in the sandwich?", zh: "你想在三明治里放什么？" },
        { en: "I'd like some chicken.", zh: "我想要一些鸡肉。" },
        { en: "What would you like to drink?", zh: "你想喝什么？" },
        { en: "I'd like some orange juice.", zh: "我想要一些橙汁。" },
      ],
      lines: [
        { name: "Mum", role: "adultFemale", text: "What would you like in the sandwich?", zh: "你想在三明治里放什么？" },
        { name: "Mike", role: "boyChild", text: "I'd like some chicken. I love meat! It makes me strong.", zh: "我想要一些鸡肉。我爱吃肉！它让我强壮。" },
        { name: "Mum", role: "adultFemale", text: "OK.", zh: "好的。" },
        { name: "Mike", role: "boyChild", text: "And some tomatoes, please.", zh: "再来一些番茄，请。" },
        { name: "Mum", role: "adultFemale", text: "Great! Vegetables are healthy food. They are good for you.", zh: "太好了！蔬菜是健康食品。对你有好处。" },
        { name: "Mum", role: "adultFemale", text: "What would you like to drink?", zh: "你想喝什么？" },
        { name: "Mike", role: "boyChild", text: "I'd like some orange juice, Mum.", zh: "我想要一些橙汁，妈妈。" },
        { name: "Mum", role: "adultFemale", text: "Sorry, we don't have any orange juice. How about grape juice?", zh: "抱歉，我们没有橙汁。葡萄汁怎么样？" },
        { name: "Mike", role: "boyChild", text: "Great! I love grape juice, too.", zh: "太好了！我也爱葡萄汁。" },
      ],
    },
    2: {
      title: "What Would You Like to Have?",
      bookPages: [53, 54],
      focusTalk:
        "餐厅点餐加长一点。What would you like to have？I'd like to have some rice with…。dessert 是甜点。Ice cream! That's my favourite。中餐西餐词汇先认得，上课表演点餐不卡壳。",
      keySentences: [
        { en: "What would you like to have?", zh: "你想吃什么？" },
        { en: "I'd like to have some rice with potatoes and meatballs.", zh: "我想要米饭配土豆和肉丸。" },
        { en: "I'd like to try something different today.", zh: "今天我想试点不一样的。" },
        { en: "Ice cream! That's my favourite.", zh: "冰淇淋！那是我的最爱。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Let's have lunch here.", zh: "我们在这儿吃午饭吧。" },
        { name: "Baobao", role: "boyChild", text: "OK. What would you like to have?", zh: "好。你想吃什么？" },
        { name: "Mike", role: "boyChild", text: "I'd like to have some rice with potatoes and meatballs. I love Chinese food. What would you like to eat, Baobao?", zh: "我想要米饭配土豆和肉丸。我爱中国菜。你想吃什么，宝宝？" },
        { name: "Baobao", role: "boyChild", text: "Well, I'd like to try something different today. I want to have some steak and tomato soup.", zh: "嗯，今天我想试点不一样的。我想要牛排和番茄汤。" },
        { name: "Mike", role: "boyChild", text: "And for dessert?", zh: "那甜点呢？" },
        { name: "Baobao", role: "boyChild", text: "Ice cream! That's my favourite.", zh: "冰淇淋！那是我的最爱。" },
      ],
    },
    3: {
      title: "Please Don't Play with the Chopsticks",
      bookPages: [56, 57],
      focusTalk:
        "餐桌礼仪。Please don't play with the chopsticks。筷子是 hold them in one hand and pick up food。刀叉：knife in the right hand，fork in the left hand。上课演示怎么用筷子和刀叉，用这些句子说明。",
      keySentences: [
        { en: "Please don't play with the chopsticks.", zh: "请不要玩筷子。" },
        { en: "How do I use the chopsticks?", zh: "我怎么用筷子？" },
        { en: "We hold them in one hand and pick up food like this.", zh: "我们单手拿着它们，像这样夹起食物。" },
        { en: "We often hold the knife in the right hand and the fork in the left hand.", zh: "我们常常右手拿刀，左手拿叉。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Kevin, be quiet. Please don't play with the chopsticks.", zh: "Kevin，安静。请不要玩筷子。" },
        { name: "Kevin", role: "boyChild", text: "Sorry, but how do I use the chopsticks?", zh: "对不起，可我怎么用筷子呢？" },
        { name: "Mike", role: "boyChild", text: "We don't play with them. We hold them in one hand and pick up food like this.", zh: "我们不拿它们玩。单手拿着，像这样夹起食物。" },
        { name: "Kevin", role: "boyChild", text: "OK, let me try.", zh: "好，让我试试。" },
        { name: "Kevin", role: "boyChild", text: "How do you cut the steak with knife and fork?", zh: "你怎么用刀叉切牛排？" },
        { name: "Mike", role: "boyChild", text: "Well, we often hold the knife in the right hand and the fork in the left hand.", zh: "嗯，我们常常右手拿刀，左手拿叉。" },
        { name: "Kevin", role: "boyChild", text: "Thank you, Mike.", zh: "谢谢你，Mike。" },
      ],
    },
    4: {
      title: "How to Make Fruit Salad",
      bookPages: [59, 60],
      focusTalk:
        "顺序词是重点：First, Next, Then, Last。做水果沙拉：First, wash the fruit. Next, cut… Then, put… Last, put ice cream…。上课说制作步骤，一定要按这个顺序。",
      keySentences: [
        { en: "First, wash the fruit.", zh: "首先，洗水果。" },
        { en: "Next, cut the apple, banana, pear and the grapes.", zh: "接着，切开苹果、香蕉、梨和葡萄。" },
        { en: "Then, put all the fruit on a plate.", zh: "然后，把所有水果放在盘子上。" },
        { en: "Last, put ice cream on the fruit.", zh: "最后，把冰淇淋放在水果上。" },
      ],
      lines: [
        { name: "Speaker", role: "girlChild", text: "Let's get the food: one apple, one banana, one pear, some grapes, some ice cream.", zh: "我们准备食材：一个苹果、一根香蕉、一个梨、一些葡萄、一些冰淇淋。" },
        { name: "Speaker", role: "girlChild", text: "Let's make the fruit salad.", zh: "我们来做水果沙拉。" },
        { name: "Speaker", role: "girlChild", text: "First, wash the fruit.", zh: "首先，洗水果。" },
        { name: "Speaker", role: "girlChild", text: "Next, cut the apple, banana, pear and the grapes.", zh: "接着，切开苹果、香蕉、梨和葡萄。" },
        { name: "Speaker", role: "girlChild", text: "Then, put all the fruit on a plate.", zh: "然后，把所有水果放在盘子上。" },
        { name: "Speaker", role: "girlChild", text: "Last, put ice cream on the fruit. Make the salad look nice.", zh: "最后，把冰淇淋放在水果上。让沙拉好看一点。" },
        { name: "Speaker", role: "girlChild", text: "Now, let's enjoy the fruit salad!", zh: "现在，我们来享用水果沙拉吧！" },
      ],
    },
  },
  u6: {
    1: {
      title: "We Can't Live Without Nature",
      bookPages: [64, 65],
      focusTalk:
        "大自然是什么？plants, animals, air and the sun。关键句：Nature is all around us. We can't live without nature。上课讨论没有空气、太阳能不能活，就用 can't live without。",
      keySentences: [
        { en: "What is nature?", zh: "什么是自然？" },
        { en: "Nature is all around us.", zh: "大自然就在我们身边。" },
        { en: "We can't live without nature.", zh: "没有大自然我们无法生活。" },
      ],
      lines: [
        { name: "Mike", role: "boyChild", text: "Maomao, look! The film Nature Is Speaking is on.", zh: "毛毛，看！电影《自然在说话》在上映。" },
        { name: "Maomao", role: "boyChild", text: "Emm, but what is nature, Mike?", zh: "嗯，可是什么是自然，Mike？" },
        { name: "Mike", role: "boyChild", text: "Trees? Birds? … I'm not so sure.", zh: "树？鸟？……我不太确定。" },
        { name: "Maomao", role: "boyChild", text: "Let's find out on the Internet.", zh: "我们上网查一查吧。" },
        { name: "Mike", role: "boyChild", text: "Look. It says here: Almost everything is nature — plants, animals, air and the sun …", zh: "看。这里写着：几乎一切都是自然——植物、动物、空气和太阳……" },
        { name: "Maomao", role: "boyChild", text: "I see. Nature is all around us. We can't live without nature.", zh: "我明白了。大自然就在身边。没有自然我们无法生活。" },
        { name: "Mike", role: "boyChild", text: "But what would nature say to us? Let's go and see the film.", zh: "可自然会对我们说什么？我们去看电影吧。" },
      ],
    },
    2: {
      title: "Feel Nature on the Farm",
      bookPages: [67, 68],
      focusTalk:
        "农场日记：I can feel nature. 动作词 milk the cows、collect eggs、feed the pigs。还会 smell the flowers、look at the stars、hear the sheep。上课说你在农场做什么，用这些动词。",
      keySentences: [
        { en: "I can feel nature.", zh: "我能感受到自然。" },
        { en: "I milk the cows, collect eggs, feed the pigs and eat fruit.", zh: "我挤牛奶、收鸡蛋、喂猪，还吃水果。" },
        { en: "I smell the flowers and look at the stars.", zh: "我闻花香，看星星。" },
      ],
      lines: [
        { name: "Guoguo", role: "girlChild", text: "I am on my uncle's farm now. I can feel nature. It is all around me.", zh: "我现在在叔叔的农场。我能感受到自然。它就在我身边。" },
        { name: "Guoguo", role: "girlChild", text: "Every day, I milk the cows, collect eggs, feed the pigs and eat fruit. It's so much fun.", zh: "每天我挤牛奶、收鸡蛋、喂猪，还吃水果。真有趣。" },
        { name: "Guoguo", role: "girlChild", text: "Sometimes, I smell the flowers in the morning and look at the stars at night. They are all beautiful.", zh: "有时早上我闻花香，晚上看星星。它们都很美。" },
        { name: "Guoguo", role: "girlChild", text: "Listen! \"Baa…\" Can you hear that? It's the sheep. They're calling me to feed them.", zh: "听！「咩……」你听见了吗？是羊。它们在叫我去喂它们。" },
        { name: "Guoguo", role: "girlChild", text: "What a wonderful time!", zh: "多么美妙的时光！" },
      ],
    },
    3: {
      title: "Snow Turns into Water",
      bookPages: [70, 71],
      focusTalk:
        "科学小对话。turns into 是变成。水汽在玻璃上变冷 turns into ice。太阳出来 Snow turns into water。上课解释冰和雪怎么变化，抓住 turns into。",
      keySentences: [
        { en: "It's so cold today.", zh: "今天好冷。" },
        { en: "The water in the air gets cold on the glass. It turns into ice.", zh: "空气中的水在玻璃上变冷，变成了冰。" },
        { en: "Snow turns into water.", zh: "雪变成水。" },
      ],
      lines: [
        { name: "Child A", role: "girlChild", text: "It's so cold today.", zh: "今天好冷。" },
        { name: "Child B", role: "boyChild", text: "Yes. I can see your red nose. Haha!", zh: "是啊。我看见你的红鼻子了。哈哈！" },
        { name: "Child A", role: "girlChild", text: "Look! There is ice on the window.", zh: "看！窗户上有冰。" },
        { name: "Child B", role: "boyChild", text: "Wow, so beautiful! Why is there ice?", zh: "哇，好美！为什么有冰？" },
        { name: "Child A", role: "girlChild", text: "The room is warm, and the glass is cold. The water in the air gets cold on the glass. It turns into ice.", zh: "房间暖，玻璃冷。空气中的水在玻璃上变冷，就变成了冰。" },
        { name: "Child B", role: "boyChild", text: "Look, it's snowing outside. I love snow.", zh: "看，外面下雪了。我爱雪。" },
        { name: "Child A", role: "girlChild", text: "Me, too. Let's go out and have fun after class.", zh: "我也是。下课我们出去玩吧。" },
        { name: "Child B", role: "boyChild", text: "Oh, no! The sun comes out. Snow turns into water.", zh: "哦，不！太阳出来了。雪变成了水。" },
        { name: "Child A", role: "girlChild", text: "That's too bad!", zh: "太糟糕了！" },
      ],
    },
    4: {
      title: "I Love This Trip",
      bookPages: [73, 74],
      focusTalk:
        "旅行路线：We start … walk into the forest and cross the grasslands. go over the river。最后 I love this trip。上课说旅行经过哪里，用 start、cross、go over。",
      keySentences: [
        { en: "Where are we going?", zh: "我们要去哪里？" },
        { en: "We start this trip from Xishuangbanna.", zh: "我们从西双版纳开始这次旅行。" },
        { en: "We walk into the forest and cross the grasslands.", zh: "我们走进森林，穿过草原。" },
        { en: "I love this trip.", zh: "我喜欢这次旅行。" },
      ],
      lines: [
        { name: "Child", role: "boyChild", text: "Where are we going, Dad?", zh: "我们要去哪里，爸爸？" },
        { name: "Dad", role: "adultMale", text: "The world is so big. Let's go and see.", zh: "世界很大。我们去看看吧。" },
        { name: "Dad", role: "adultMale", text: "We start this trip from Xishuangbanna, Yunnan.", zh: "我们从云南西双版纳开始这次旅行。" },
        { name: "Child", role: "boyChild", text: "I'm excited about everything on the way.", zh: "我对一路上的一切都很兴奋。" },
        { name: "Dad", role: "adultMale", text: "We walk into the forest and cross the grasslands.", zh: "我们走进森林，穿过草原。" },
        { name: "Child", role: "boyChild", text: "We are big stars. People take photos of us.", zh: "我们成了大明星。人们给我们拍照。" },
        { name: "Child", role: "boyChild", text: "Where do we go next, Dad?", zh: "我们接下来去哪儿，爸爸？" },
        { name: "Dad", role: "adultMale", text: "We go over the Yuanjiang River and stop at Pu'er, Yunnan.", zh: "我们过元江，停在云南普洱。" },
        { name: "Child", role: "boyChild", text: "We enjoy nice food and cool water. Later, we get to Yuxi and then Kunming.", zh: "我们享受美食和凉水。后来到玉溪，再到昆明。" },
        { name: "Dad", role: "adultMale", text: "It's time to go home.", zh: "该回家了。" },
        { name: "Child", role: "boyChild", text: "I love this trip.", zh: "我喜欢这次旅行。" },
      ],
    },
  },
  u7: {
    1: {
      title: "Happy New Year!",
      bookPages: [78, 79],
      focusTalk:
        "新年问候 Happy New Year！谈目标：What's your New Year's goal？I want to… / I'd like to…。日期 Today is January 1st。上课说自己的新年目标，用 I'd like to。",
      keySentences: [
        { en: "Happy New Year!", zh: "新年快乐！" },
        { en: "What's your New Year's goal?", zh: "你的新年目标是什么？" },
        { en: "I want to read more than fifty books.", zh: "我想读五十多本书。" },
        { en: "I'd like to help sixty people!", zh: "我想帮助六十个人！" },
      ],
      lines: [
        { name: "Friends", role: "girlChild", text: "Happy New Year!", zh: "新年快乐！" },
        { name: "Sara", role: "girlChild", text: "Hello, Peter!", zh: "你好，Peter！" },
        { name: "Peter", role: "boyChild", text: "Hey, Sara. Happy New Year from New York! Look!", zh: "嘿，Sara。纽约祝你新年快乐！看！" },
        { name: "Sara", role: "girlChild", text: "Wow, beautiful fireworks!", zh: "哇，美丽的烟花！" },
        { name: "Lingling", role: "girlChild", text: "Here's a New Year's gift for you.", zh: "这是给你的新年礼物。" },
        { name: "Sara", role: "girlChild", text: "Thank you!", zh: "谢谢！" },
        { name: "Lingling", role: "girlChild", text: "Today is January 1st in China. A new year begins. What's your New Year's goal?", zh: "今天是中国的一月一日。新的一年开始了。你的新年目标是什么？" },
        { name: "Sara", role: "girlChild", text: "I want to read more than fifty books. And you?", zh: "我想读五十多本书。你呢？" },
        { name: "Lingling", role: "girlChild", text: "I'd like to help sixty people!", zh: "我想帮助六十个人！" },
        { name: "Peter", role: "boyChild", text: "Cool! I'd like to learn 100 Chinese characters in the new year.", zh: "酷！我想在新的一年学会一百个汉字。" },
      ],
    },
    2: {
      title: "Happy Spring Festival!",
      bookPages: [81, 82],
      focusTalk:
        "春节：The Spring Festival is coming. Could you come for dinner…？压岁钱 lucky money，祝福 I wish you good luck！「福」means good luck。上课介绍春节习俗，用 wish 和 lucky money。",
      keySentences: [
        { en: "The Spring Festival is coming.", zh: "春节就要到了。" },
        { en: "Could you come for dinner with my family tomorrow evening?", zh: "明天晚上你能来和我家人一起吃晚饭吗？" },
        { en: "Happy Spring Festival!", zh: "春节快乐！" },
        { en: "I wish you good luck!", zh: "我祝你好运！" },
      ],
      lines: [
        { name: "Yangyang", role: "boyChild", text: "Hi, Sara.", zh: "嗨，Sara。" },
        { name: "Sara", role: "girlChild", text: "Hello, Yangyang. What's up?", zh: "你好，阳阳。怎么了？" },
        { name: "Yangyang", role: "boyChild", text: "The Spring Festival is coming. Could you come for dinner with my family tomorrow evening?", zh: "春节就要到了。明天晚上你能来和我家人一起吃晚饭吗？" },
        { name: "Sara", role: "girlChild", text: "Thank you. I'd love to.", zh: "谢谢。我很乐意。" },
        { name: "Mrs Li", role: "adultFemale", text: "Nice work, Sara!", zh: "做得真好，Sara！" },
        { name: "Sara", role: "girlChild", text: "It's my first time to make jiaozi, Mrs Li.", zh: "这是我第一次包饺子，李阿姨。" },
        { name: "Mrs Li", role: "adultFemale", text: "Happy Spring Festival, Sara! Here's the lucky money for you. I wish you good luck!", zh: "春节快乐，Sara！这是给你的压岁钱。我祝你好运！" },
        { name: "Yangyang", role: "boyChild", text: "\"Fu\" in Chinese means \"good luck\". Good luck to everyone!", zh: "中文里的「福」是好运的意思。祝大家好运！" },
      ],
    },
    3: {
      title: "Happy Lantern Festival!",
      bookPages: [84, 85],
      focusTalk:
        "元宵节通常在 February。活动：watch the lantern show，guess the lantern riddle。yuanxiao 像雪球，「圆」means together。上课猜谜、介绍元宵节用这些词。",
      keySentences: [
        { en: "The Lantern Festival is coming!", zh: "元宵节就要到了！" },
        { en: "We watch the lantern show.", zh: "我们看花灯展。" },
        { en: "It's a lantern riddle. Let's guess.", zh: "这是灯谜。我们来猜。" },
        { en: "\"Yuan\" in Chinese means \"together\".", zh: "中文里的「圆」是团圆、在一起的意思。" },
      ],
      lines: [
        { name: "Child A", role: "girlChild", text: "The Lantern Festival is coming!", zh: "元宵节就要到了！" },
        { name: "Child B", role: "boyChild", text: "When is it?", zh: "它在什么时候？" },
        { name: "Child A", role: "girlChild", text: "It is usually in February.", zh: "它通常在二月。" },
        { name: "Child B", role: "boyChild", text: "What do you do on this festival?", zh: "这个节日你们做什么？" },
        { name: "Child A", role: "girlChild", text: "We watch the lantern show.", zh: "我们看花灯展。" },
        { name: "Child B", role: "boyChild", text: "Happy Lantern Festival! So many beautiful lanterns! Oh, look! What's that?", zh: "元宵节快乐！好多糖美的灯！哦，看！那是什么？" },
        { name: "Child A", role: "girlChild", text: "It's a lantern riddle. Let's guess.", zh: "这是灯谜。我们来猜。" },
        { name: "Riddle", role: "adultFemale", text: "I'm a kind of food. I look like a snowball, but I'm not cold. What am I?", zh: "我是一种食物。我看起来像雪球，可我不冷。我是什么？" },
        { name: "Child B", role: "boyChild", text: "Haha! It's yuanxiao!", zh: "哈哈！是元宵！" },
        { name: "Child A", role: "girlChild", text: "Let's eat yuanxiao. \"Yuan\" in Chinese means \"together\".", zh: "我们吃元宵吧。「圆」在中文里是团圆的意思。" },
        { name: "Child B", role: "boyChild", text: "Look, they really look like snowballs. How cute!", zh: "看，它们真的像雪球。好可爱！" },
      ],
    },
    4: {
      title: "The Story of Nian",
      bookPages: [87, 88],
      focusTalk:
        "年兽故事：Nian is afraid of the red colour and loud sounds。人们 put on red clothes and set off firecrackers。最后 Nian runs away。上课复述故事，按 Long long ago → Every year → One year → The next year → At last 顺序说。",
      keySentences: [
        { en: "His name is Nian.", zh: "它的名字叫年。" },
        { en: "Nian is afraid of the red colour and loud sounds.", zh: "年害怕红色和很大的声音。" },
        { en: "People put on red clothes and set off firecrackers.", zh: "人们穿红衣服，放鞭炮。" },
        { en: "At last, he runs away and never comes back.", zh: "最后，它跑掉了，再也不回来。" },
      ],
      lines: [
        { name: "Narrator", role: "adultFemale", text: "People wear red clothes and set off firecrackers during the Spring Festival. Do you know why? Here's a story.", zh: "春节人们穿红衣服、放鞭炮。你知道为什么吗？这里有一个故事。" },
        { name: "Narrator", role: "adultFemale", text: "Long, long ago, there is a big monster. His name is Nian.", zh: "很久很久以前，有一个大妖怪。它的名字叫年。" },
        { name: "Narrator", role: "adultFemale", text: "Every year, he comes out to hurt people and animals. People are afraid.", zh: "每年它出来伤害人和动物。人们很害怕。" },
        { name: "Narrator", role: "adultFemale", text: "One year, a man finds out Nian is afraid of the red colour and loud sounds. So he tells everyone.", zh: "有一年，一个人发现年害怕红色和大声。于是他告诉了大家。" },
        { name: "Narrator", role: "adultFemale", text: "The next year, people put on red clothes and set off firecrackers. Nian is afraid.", zh: "第二年，人们穿上红衣服，放鞭炮。年害怕了。" },
        { name: "Narrator", role: "adultFemale", text: "At last, he runs away and never comes back.", zh: "最后，它跑掉了，再也不回来。" },
      ],
    },
  },
  u8: {
    1: {
      title: "Revision A",
      bookPages: [92, 93],
      focusTalk:
        "总复习：食物词、新年目标 I'd like to / I want to，还有春节前家里做什么。把 I'd like some…、We can't live without…、I wish… 再读熟，开学后单元检测更稳。",
      keySentences: [
        { en: "I'd like to get better at kung fu.", zh: "我想把功夫练得更好。" },
        { en: "I want to plant more trees.", zh: "我想种更多的树。" },
        { en: "I'd like to help sixty people.", zh: "我想帮助六十个人。" },
      ],
      lines: [
        { name: "Friend A", role: "boyChild", text: "I want to plant more trees.", zh: "我想种更多的树。" },
        { name: "Friend B", role: "girlChild", text: "I'd like to get better at kung fu.", zh: "我想把功夫练得更好。" },
        { name: "Friend C", role: "boyChild", text: "I'd like to help sixty people.", zh: "我想帮助六十个人。" },
        { name: "Friend D", role: "girlChild", text: "I want to be tall and strong.", zh: "我想长得又高又壮。" },
        { name: "Teacher", role: "adultFemale", text: "What do your family do before the Spring Festival?", zh: "春节前你的家人做什么？" },
        { name: "Student", role: "boyChild", text: "We clean the house and buy food.", zh: "我们打扫房子，买食物。" },
        { name: "Teacher", role: "adultFemale", text: "What do your family have at the big dinner?", zh: "年夜饭你们家吃什么？" },
        { name: "Student", role: "girlChild", text: "We have jiaozi and chicken.", zh: "我们吃饺子和鸡肉。" },
      ],
    },
    2: {
      title: "Revision B",
      bookPages: [94, 95],
      focusTalk:
        "对比春节和 Christmas。都会家人团聚 big festival、big dinner。中国有 jiaozi、lucky money；美国有 turkey、Christmas tree、Santa。预习时会比较两个节日，上课说 Both … and … / During …。",
      keySentences: [
        { en: "The Spring Festival is a big festival in China.", zh: "春节是中国的重大节日。" },
        { en: "Christmas is a big festival in the USA.", zh: "圣诞节是美国的重大节日。" },
        { en: "All the family get together at Christmas.", zh: "圣诞节全家人聚在一起。" },
      ],
      lines: [
        { name: "Child", role: "boyChild", text: "The Spring Festival is a big festival in China. What's your big festival, Sara?", zh: "春节是中国的重大节日。你的重大节日是什么，Sara？" },
        { name: "Sara", role: "girlChild", text: "Christmas is a big festival in the USA.", zh: "圣诞节是美国的重大节日。" },
        { name: "Sara", role: "girlChild", text: "All the family get together at Christmas.", zh: "圣诞节全家人聚在一起。" },
        { name: "Sara", role: "girlChild", text: "We decorate our Christmas tree.", zh: "我们装饰圣诞树。" },
        { name: "Sara", role: "girlChild", text: "On Christmas Eve, we have turkey and other food for our big dinner.", zh: "平安夜我们吃火鸡和其他食物作为大餐。" },
        { name: "Sara", role: "girlChild", text: "Before we go to sleep, we hang up stockings.", zh: "睡觉前，我们挂起长袜。" },
        { name: "Sara", role: "girlChild", text: "At night, Santa brings us gifts. We are so happy.", zh: "夜里，圣诞老人给我们带来礼物。我们非常开心。" },
      ],
    },
  },
};
